---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s0-service-a-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0-service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0-service-a
      touchpoint: touchpoint
  template:
    metadata:
      labels:
        app: s0-service-a            # specific (different per image)
        touchpoint: touchpoint # generic  (same for all image)
    spec:
      serviceAccountName: s0-service-a-sa
      containers:
      - name: s0-service-a-co
        image: patrice1972/s0-service-a:1.0.0
        ports:
        - protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: touchpoint
spec:
  selector:
    touchpoint: touchpoint
  ports:
  - name: http-touchpoint # It's MANDATORY to have a NAMED port starting with 'http-'
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s0-client-x-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0-client-x-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0-client-x
  template:
    metadata:
      labels:
        app: s0-client-x
    spec:
      serviceAccountName: s0-client-x-sa
      containers:
      - name: s0-client-x-co
        image: patrice1972/s0-client-x:1.0.0
        env:
        - name: API_HOST
          value: "api.company.com"
        - name: API_PORT
          value: "8080"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: destination-rule
spec:
  host: touchpoint.default.svc.cluster.local
  subsets:
  - name: s0-service-a-ss
    labels:
      app: s0-service-a
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: one-virtual-service
spec:
  hosts:
  - api.company.com
  http:
  - name: "get-path-zenlo-01"
    match:
    - method:
        exact: GET
      uri:
        exact: "/path-zenlo-01"
    route:
    - destination:
        host: touchpoint.default.svc.cluster.local
        subset: s0-service-a-ss
