---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s0-service-a-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0-service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0-service-a
  template:
    metadata:
      labels:
        app: s0-service-a
    spec:
      serviceAccountName: s0-service-a-sa
      containers:
      - name: s0-service-a-co
        image: patrice1972/s0-service-a:1.0.0
        ports:
        - protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: s0-service-a
spec:
  selector:
    app: s0-service-a
  ports:
  - name: http-s0-service-a # This is MANDATORY !!!
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s0-service-b-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0-service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0-service-b
  template:
    metadata:
      labels:
        app: s0-service-b
    spec:
      serviceAccountName: s0-service-b-sa
      containers:
      - name: s0-service-b-co
        image: patrice1972/s0-service-b:1.0.0
        ports:
        - protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: s0-service-b
spec:
  selector:
    app: s0-service-b
  ports:
  - name: http-s0-service-b # This is MANDATORY !!!
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s0-client-x-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0-client-x-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0-client-x
  template:
    metadata:
      labels:
        app: s0-client-x
    spec:
      serviceAccountName: s0-client-x-sa
      containers:
      - name: s0-client-x-co
        image: patrice1972/s0-client-x:1.0.0
        env:
        - name: API_HOST
          value: "api.company.com"
        - name: API_PORT
          value: "80"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: one-virtual-service
spec:
  hosts:
  - api.company.com
  http:
  - name: "routes-to-s0-service-a"
    match:
    - method:
        exact: GET
      uri:
        exact: "/path-zenlo-01"
    route:
    - destination:
        host: s0-service-a.default.svc.cluster.local
  - name: "routes-to-s0-service-b"
    match:
    - method:
        exact: GET
      uri:
        exact: "/path-zenlo-02"
    route:
    - destination:
        host: s0-service-b.default.svc.cluster.local
